/* this file was autogenerated by make */
#define UCLIBC_TARGET_PREFIX  "/"
#define UCLIBC_DEVEL_PREFIX  "/home/netlab/j6-harvey/lin/uClibc-0.9.20"
#define UCLIBC_BUILD_DIR  "/home/netlab/j6-harvey/lin/uClibc-0.9.20"
#define GCC_BIN  "/usr/local/bin/arm-linux-gcc"
#define LIBGCC_DIR  "/usr/local/arm/2.95.3/lib/gcc-lib/arm-linux/2.95.3/"
#define TARGET_ARCH  "arm"
#define DYNAMIC_LINKER  ""
#define BUILD_DYNAMIC_LINKER  "/home/netlab/j6-harvey/lin/uClibc-0.9.20/lib/ld-uClibc.so.0"
#undef __UCLIBC_HAS_SHARED__
#define __UCLIBC_HAS_MMU__ 1
#undef __HAS_ELF__
#define __UCLIBC_CTOR_DTOR__ 1
#define __UCLIBC_PROFILING__ 1
